version: '3'

services:
  master-node:
    container_name: master-node
    image: "vineetleeway/cosmos:v3"
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    volumes:
      - $PWD/run_master.sh:/root/run_master.sh
      - $PWD/aws_configure.sh:/root/aws_configure.sh
    command: /bin/sh run_master.sh $TENANT_BRANCH $AWS_KEY $AWS_SECRET $REGION $APP_ID
    environment:
      - "TENANT_BRANCH=${TENANT_BRANCH}"
      - "AWS_KEY=${AWS_KEY}"
      - "AWS_SECRET=${AWS_SECRET}"
      - "REGION=${REGION}"
      - "APP_ID=${APP_ID}"
    networks:
      devnet:
        ipv4_address: 192.168.21.2

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.21.0/24